### PR TITLE
Speed up CI

### PR DESCRIPTION
**Pull request by AvinashBukkittu**
This PR is an attempt to speed up CI

- Removes TF dependency

### CODE REVIEW

**Comment by gpengzhi** [comment]
@AvinashBukkittu Thanks for the fix! Do we plan to merge it?

**Comment by AvinashBukkittu** [comment]
> @AvinashBukkittu Thanks for the fix! Do we plan to merge it?

Not yet. We can try out a few things to see how we can reduce the running time. Few of the possible things we can try are

- Try to parallelize `pytest`
- Instead of installing the libraries every time, I was wondering if we can dockerize it and cache the docker image or something
- Try splitting the jobs into smaller jobs

**Comment by gpengzhi** [comment]
Sounds great. Maybe you could set up CI in your forked repo so that you can try things there at first.

**Comment by huzecong** [comment]
Can we close this in favor of #148?

**Comment by AvinashBukkittu** [comment]
> Can we close this in favor of #148?

Sure, I will close it for now. But I think even without tensorflow it takes 10min. I will try to make it faster in the future. But it is of low priority right now.

**Pull request closed without merging**
